name: dsrpt21_app
description: Aplicativo em flutter para a criação de robôs.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.10
  path_provider: ^1.4.5
  image_picker: ^0.6.7+14
  mobx:
  flutter_mobx:

  cupertino_icons: ^0.1.3

dev_dependencies:
  mobx_codegen:
  build_runner:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
      - radial_scale.png
      - robot.png
